extends: "airbnb-base"

parserOptions:
  ecmaVersion: 2018

env:
  browser: true
  jquery: true
  node: true

rules:
  no-console: off # console.log などを許可
  no-alert: off # alert, confirm などを許可
  quotes: ["warn", "single", { "allowTemplateLiterals": true }] # `` で囲むのがテンプレートリテラル
  no-unused-vars: warn
  func-names: ["error", "as-needed"]
